FORMAT: 1A

# MFS API
API for unit testing *MFS*

# LOGIN
**MSF API** is static API

## Login [/mfs-server/j_spring_security_check]
### Login request [POST]
+ Request (application/json)

        { "j_password": "test101",
		  "j_username" : "Test101",
		  "submit" : "submit"}

+ Response 302 (application/json)

        { "JSESSIONID" : "66B46BB54A43B97BFB86F09B00E2F625",
		 "Path" : "/mfs-server" }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
